[app]
primary_region = "ewr"

[build]
  [build.args]
    RUBY_VERSION = "3.3.0"
    NODE_VERSION = "18.19.1"

[env]
  PORT = "8080"
  RAILS_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
